server:
  port: 9527


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启动态路由
      routes:
        - id: payment_routh         #路由的id，没有固定规则但要求唯一，建议配合服务名
         # uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**     #断言， 路径相匹配的进行路由

        - id: payment_routh2
         # uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/create/**


eureka:
  instance:
    hostname: cloud-gateway-server
  client:
    #false表示不向服务端注册自己
    register-with-eureka: true
    #false 表示自己端就是注册中心，维护服务实例，不需要检索服务
    fetch-registry: true
    #设置与eureka server 交互的地址,查询服务和注册服务都需要这个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/



