server:
  port: 80

eureka:
  client:
    #false表示不向服务端注册自己
    register-with-eureka: true
    #false 表示自己端就是注册中心，维护服务实例，不需要检索服务
    fetch-registry: true
    #设置与eureka server 交互的地址,查询服务和注册服务都需要这个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

